Only handle Emscripten exceptions, let pure JS exceptions propagate
...or at least any JS exceptions derived from Error.  (TODO: Is there a better
way to tell Emscripten from pure JS exceptions?)

At least with emsdk 3.1.46, calling getExceptionMessage on a non-Emscripten
exception causes a

> TypeError: ex.getArg is not a function
>     at getCppExceptionThrownObjectFromWebAssemblyException
>     at getExceptionMessage

and I ran into that now when I started to implement a jsuno wrapper around
Module.unoObject (which caused some JS exceptions, that then propagated down
through the JS - C++ - JS call stack).